name: hexlet-application

on: push

jobs:
  build:
    runs-on: ubuntu/latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: make setup
      - name: start tests
        run: make test
      - name: start lint
        run: make lint
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: on cache
        uses: actions/setup-node@v3
        with:
          cache: npm
